apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: chat-service
  name: chat-service
spec:
  containers:
  - image: cc_chat_v1
    name: chat-service
    ports:
    - containerPort: 3000
    resources: {}
  restartPolicy: OnFailure
status: {}
