version: "3"
services: 
    chat-service:
      build: ./cc_chat_v1
      restart: on-failure
      ports: 
        - "80:3000"
      networks: 
        - app_logindata
    logindb:
      image: mongo:latest
      container_name: logindb
      volumes:
        - logindb:/data/db
      networks: 
        - mongo_maintenance
        - app_logindata
        - mongo_seed
    logindb-seed:
      build: ./login_db-seed
      volumes:
        - logindb:/data/db
      networks: 
        - mongo_seed
    mongo-express:
      image: mongo-express:latest
      environment:
        - ME_CONFIG_MONGODB_SERVER=logindb
        - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
        - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_ROOT_USER}
        - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_ROOT_PASSWORD}
        - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
        - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
      env_file: 
        - .env
      restart: on-failure
      ports:
        - "8081:8081"
      networks: 
        - mongo_maintenance

volumes:
  logindb:
networks: 
  app_logindata:
  mongo_maintenance:
  mongo_seed:


